/* Author: Kyra Phillips
   Due Date: 10/19/2017 - submitting following feedback of HW3 on 10/29/2017
   Help from/Worked with: Myself, Cooper Stevens, Mark Ortleb
   Assignment: Homework Assignment #4
*/

--Query #1 How many passengers departed Colorado on all airlines?
--Sum
SELECT SUM(PASSENGERS)
FROM Cities NATURAL JOIN States NATURAL JOIN Airport NATURAL JOIN Airline NATURAL JOIN Flight
WHERE ORIGIN_STATE_ABR = 'CO'; 
--Output 
SELECT CITY_NAME, STATE_NAME, AIRPORT_ID, CARRIER_NAME, PASSENGERS
FROM Cities NATURAL JOIN States NATURAL JOIN Airport NATURAL JOIN Airline NATURAL JOIN Flight
WHERE ORIGIN_STATE_ABR = 'CO'; 

--Query #2 How much freight departed Colorado?
--SUM 
 SELECT SUM(FREIGHT)
 FROM Cities NATURAL JOIN States NATURAL JOIN Airport NATURAL JOIN Airline NATURAL JOIN Freight 
 WHERE ORIGIN_STATE_ABR = 'CO';
--Output 
 SELECT CITY_NAME, STATE_NAME, AIRPORT_ID, CARRIER_NAME, FREIGHT
 FROM Cities NATURAL JOIN States NATURAL JOIN Airport NATURAL JOIN Airline NATURAL JOIN Freight 
 WHERE ORIGIN_STATE_ABR = 'CO';

--Query #3 How many people arrived in CO from outside CO 
--Sum
 SELECT SUM(PASSENGERS)
 FROM CITIES NATURAL JOIN AIRPORT NATURAL JOIN AIRLINE NATURAL JOIN FLIGHT 
 WHERE ORIGIN_STATE_ABR != 'CO' AND DEST_STATE_ABR = 'CO';
--Output
 SELECT CITY_NAME, ORIGIN_STATE_ABR, DEST_STATE_ABR, AIRPORT_ID, CARRIER_NAME, PASSENGERS
 FROM CITIES NATURAL JOIN AIRPORT NATURAL JOIN AIRLINE NATURAL JOIN FLIGHT 
 WHERE ORIGIN_STATE_ABR != 'CO' AND DEST_STATE_ABR = 'CO';

--Query #4 List the flights that landed in Denver and had traveled more than 500 miles, but less than 1200 
-- Output
SELECT CITY_NAME, ORIGIN_STATE_ABR, CARRIER_NAME, DISTANCE 
FROM CITIES NATURAL JOIN AIRPORT NATURAL JOIN AIRLINE NATURAL JOIN FLIGHT 
WHERE CITY_NAME LIKE '%Denver%' AND DISTANCE>500 AND DISTANCE<1200;

