/* Author: Kyra Phillips
   Due Date: 10/8/2017 - resubmitting 12/3/2017
   Help from/Worked with: Myself, Cooper Stevens
   Assignment: Homework Assignment #3
*/

-- Create SQL Statements, part one to HW3

--Table one is for all of the necessary information pertaining to airlines 

CREATE TABLE Airline(AIRLINE_ID VARCHAR(10),CARRIER VARCHAR(10),CARRIER_ENTITY VARCHAR(10),CARRIER_NAME VARCHAR(200), UNIQUE_CARRIER VARCHAR(100), UNIQUE_CARRIER_ENTITY VARCHAR(100),
	 UNIQUE_CARRIER_NAME VARCHAR(200), WAC VARCHAR(50), CARRIER_GROUP VARCHAR(50), CARRIER_GROUP_NEW VARCHAR(100), REGION VARCHAR(150), START_DATE_SOURCE VARCHAR(150), 
	 THRU_DATE_SOURCE VARCHAR(150), 
	 FOREIGN KEY (UNIQUE_CARRIER_ENTITY) REFERENCES Carrier (UNIQUE_CARRIER_ENTITY) );
	 
--Table two holds the basic information for a carrier 

CREATE TABLE Carrier (UNIQUE_CARRIER_ENTITY VARCHAR(10), WAC VARCHAR(5), CARRIER_GROUP VARCHAR(5), PRIMARY KEY (UNIQUE_CARRIER_ENTITY));

-- Table three holds the information that relates to the relation table 

CREATE TABLE UniqueCarrierName (UNIQUE_CARRIER VARCHAR(200), UNIQUE_CARRIER_NAME VARCHAR(200), PRIMARY KEY (UNIQUE_CARRIER));

--Relation table for the carrier information 

CREATE TABLE CarrierRelation (UNIQUE_CARRIER VARCHAR(100), CARRIER VARCHAR(100), 
	FOREIGN KEY(UNIQUE_CARRIER) REFERENCES Carrier(UNIQUE_CARRIER_ENTITY), FOREIGN KEY (CARRIER) REFERENCES UniqueCarrierName(UNIQUE_CARRIER) );

--Table for referencing and storing the airport information 

CREATE TABLE Airport (AIRPORT_ID VARCHAR(10), AIRPORT_SEQ_ID VARCHAR(10), CITY_MARKET_ID VARCHAR(10), AIRPORT_WAC VARCHAR(5), AIRPORT_NAME VARCHAR(5), PRIMARY KEY(AIRPORT_ID), FOREIGN KEY (CITY_MARKET_ID) REFERENCES Cities(CITY_MARKET_ID));

--Table for cities 

CREATE TABLE Cities (CITY_MARKET_ID VARCHAR(100), CITY_NAME VARCHAR(200), STATE_FIPS VARCHAR(200), PRIMARY KEY (CITY_MARKET_ID),FOREIGN KEY (STATE_FIPS) REFERENCES States(STATE_FIPS));

--Table for states 

CREATE TABLE States (STATE_FIPS VARCHAR(5), STATE_NAME VARCHAR(15), STATE VARCHAR(5), PRIMARY KEY (STATE_FIPS));

--Table with passengers for the flights and their locations

CREATE TABLE Passengers (UNIQUE_CARRIER_ENTITY VARCHAR(10), ORIGIN_AIRPORT_ID VARCHAR(10), DEST_AIRPORT_ID VARCHAR(10), PASSENGERS VARCHAR(5), 
	FOREIGN KEY(UNIQUE_CARRIER_ENTITY) REFERENCES Carrier(UNIQUE_CARRIER_ENTITY), FOREIGN KEY (ORIGIN_AIRPORT_ID) REFERENCES Airport(AIRPORT_ID), FOREIGN KEY (DEST_AIRPORT_ID) REFERENCES Airport(AIRPORT_ID));

--Table for freight and the required locations

CREATE TABLE Freight (UNIQUE_CARRIER_ENTITY VARCHAR(100), ORIGIN_AIRPORT_ID VARCHAR(100), DEST_AIRPORT_ID VARCHAR(100), FREIGHT VARCHAR(50),
	FOREIGN KEY(UNIQUE_CARRIER_ENTITY) REFERENCES Carrier(UNIQUE_CARRIER_ENTITY), FOREIGN KEY (ORIGIN_AIRPORT_ID) REFERENCES Airport(AIRPORT_ID), FOREIGN KEY (DEST_AIRPORT_ID) REFERENCES Airport(AIRPORT_ID));

--Table that holds mail information for the flights

CREATE TABLE Mail (UNIQUE_CARRIER_ENTITY VARCHAR(100), ORIGIN_AIRPORT_ID VARCHAR(100), DEST_AIRPORT_ID VARCHAR(100), MAIL VARCHAR(50),
	FOREIGN KEY(UNIQUE_CARRIER_ENTITY) REFERENCES Carrier(UNIQUE_CARRIER_ENTITY), FOREIGN KEY (ORIGIN_AIRPORT_ID) REFERENCES Airport(AIRPORT_ID), FOREIGN KEY (DEST_AIRPORT_ID) REFERENCES Airport(AIRPORT_ID));

--Flight table that holds referential data for each flight 

CREATE  TABLE Flight(FLIGHT_NUMBER VARCHAR(10), DISTANCE VARCHAR(10), AIR_TIME VARCHAR(10), UNIQUE_CARRIER_ENTITY VARCHAR(10), PASSENGERS VARCHAR(5), ORIGIN_STATE_ABR VARCHAR(5), DEST_STATE_ABR VARCHAR(5), PRIMARY KEY (FLIGHT_NUMBER), FOREIGN KEY (UNIQUE_CARRIER_ENTITY) REFERENCES Carrier(UNIQUE_CARRIER_ENTITY) );
